### ISSUE TITLE
Change either group or repository name

### ISSUE THREAD

**Issue by russel** [SupercomputerInABriefcase/SuperComputerInABriefcase#1]
Group uses Supercomputer, but the repository is SuperComputer. Must change one or the other for consistency.

**Comment by tomviner** [comment]
Github will sort the redirects for either a renamed org or repo, including on the website as well as git.

Supercomputer is one word, so I vote for an update of the repo name.

**Comment by russel** [comment]
I shall make the change. Hopefully all the GitHub hosted clones will change with it. Personal clones will need manual adjustment.

**Comment by tomviner** [comment]
Personal clones will still work too, just with a little warning message.
